services:
  db:
    container_name: mongodb
    image: docker.io/bitnami/mongodb:7.0
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: root
      MONGODB_DATABASE: mydatabase
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
